package pojo;
// Generated Aug 19, 2017 9:38:57 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Airline generated by hbm2java
 */
@Entity
@Table(name="Airline"
    ,catalog="let1"
)
public class Airline  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String adresa;
     private String zemlja;
     private String sajt;
     private String email;

    public Airline() {
    }

    public Airline(String name, String adresa, String zemlja, String sajt, String email) {
       this.name = name;
       this.adresa = adresa;
       this.zemlja = zemlja;
       this.sajt = sajt;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="adresa", length=150)
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    
    @Column(name="zemlja", length=150)
    public String getZemlja() {
        return this.zemlja;
    }
    
    public void setZemlja(String zemlja) {
        this.zemlja = zemlja;
    }

    
    @Column(name="sajt", length=150)
    public String getSajt() {
        return this.sajt;
    }
    
    public void setSajt(String sajt) {
        this.sajt = sajt;
    }

    
    @Column(name="email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


