package pojo;
// Generated Aug 20, 2017 3:14:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Airplane generated by hbm2java
 */
@Entity
@Table(name="Airplane"
    ,catalog="let1"
)
public class Airplane  implements java.io.Serializable {


     private Integer id;
     private String model;
     private String proizvodjac;
     private String tip;

    public Airplane() {
    }

    public Airplane(String model, String proizvodjac, String tip) {
       this.model = model;
       this.proizvodjac = proizvodjac;
       this.tip = tip;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Model", length=45)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }

    
    @Column(name="Proizvodjac", length=45)
    public String getProizvodjac() {
        return this.proizvodjac;
    }
    
    public void setProizvodjac(String proizvodjac) {
        this.proizvodjac = proizvodjac;
    }

    
    @Column(name="Tip", length=45)
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }




}


