package pojo;
// Generated Sep 12, 2017 11:43:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Flight generated by hbm2java
 */
@Entity
@Table(name="Flight"
    ,catalog="let1"
    , uniqueConstraints = @UniqueConstraint(columnNames="BrojLeta") 
)
public class Flight  implements java.io.Serializable {


     private Integer id;
     private String brojLeta;
     private String airportFrom;
     private String airportTo;
     private Date start;
     private Date time;
     private String airplane;
     private Date planiranoVreme;
     private Date ocekivanoVreme;
     private Date vremeSletanja;
     private String grad1;
     private String status;
     private String avioKompanija;
     private String grad2;
     private String izmena;
     private Integer carter;
     private String najblizi;
     private String iznajmljeno;

    public Flight() {
    }

    public Flight(String brojLeta, String airportFrom, String airportTo, Date start, Date time, String airplane, Date planiranoVreme, Date ocekivanoVreme, Date vremeSletanja, String grad1, String status, String avioKompanija, String grad2, String izmena, Integer carter, String najblizi, String iznajmljeno) {
       this.brojLeta = brojLeta;
       this.airportFrom = airportFrom;
       this.airportTo = airportTo;
       this.start = start;
       this.time = time;
       this.airplane = airplane;
       this.planiranoVreme = planiranoVreme;
       this.ocekivanoVreme = ocekivanoVreme;
       this.vremeSletanja = vremeSletanja;
       this.grad1 = grad1;
       this.status = status;
       this.avioKompanija = avioKompanija;
       this.grad2 = grad2;
       this.izmena = izmena;
       this.carter = carter;
       this.najblizi = najblizi;
       this.iznajmljeno = iznajmljeno;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="BrojLeta", unique=true, length=45)
    public String getBrojLeta() {
        return this.brojLeta;
    }
    
    public void setBrojLeta(String brojLeta) {
        this.brojLeta = brojLeta;
    }

    
    @Column(name="AirportFrom", length=45)
    public String getAirportFrom() {
        return this.airportFrom;
    }
    
    public void setAirportFrom(String airportFrom) {
        this.airportFrom = airportFrom;
    }

    
    @Column(name="AirportTo", length=45)
    public String getAirportTo() {
        return this.airportTo;
    }
    
    public void setAirportTo(String airportTo) {
        this.airportTo = airportTo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Start", length=19)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Time", length=8)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

    
    @Column(name="Airplane", length=45)
    public String getAirplane() {
        return this.airplane;
    }
    
    public void setAirplane(String airplane) {
        this.airplane = airplane;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PlaniranoVreme", length=19)
    public Date getPlaniranoVreme() {
        return this.planiranoVreme;
    }
    
    public void setPlaniranoVreme(Date planiranoVreme) {
        this.planiranoVreme = planiranoVreme;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OcekivanoVreme", length=19)
    public Date getOcekivanoVreme() {
        return this.ocekivanoVreme;
    }
    
    public void setOcekivanoVreme(Date ocekivanoVreme) {
        this.ocekivanoVreme = ocekivanoVreme;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VremeSletanja", length=19)
    public Date getVremeSletanja() {
        return this.vremeSletanja;
    }
    
    public void setVremeSletanja(Date vremeSletanja) {
        this.vremeSletanja = vremeSletanja;
    }

    
    @Column(name="Grad1", length=45)
    public String getGrad1() {
        return this.grad1;
    }
    
    public void setGrad1(String grad1) {
        this.grad1 = grad1;
    }

    
    @Column(name="Status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="AvioKompanija", length=45)
    public String getAvioKompanija() {
        return this.avioKompanija;
    }
    
    public void setAvioKompanija(String avioKompanija) {
        this.avioKompanija = avioKompanija;
    }

    
    @Column(name="Grad2", length=45)
    public String getGrad2() {
        return this.grad2;
    }
    
    public void setGrad2(String grad2) {
        this.grad2 = grad2;
    }

    
    @Column(name="Izmena", length=45)
    public String getIzmena() {
        return this.izmena;
    }
    
    public void setIzmena(String izmena) {
        this.izmena = izmena;
    }

    
    @Column(name="Carter")
    public Integer getCarter() {
        return this.carter;
    }
    
    public void setCarter(Integer carter) {
        this.carter = carter;
    }

    
    @Column(name="Najblizi", length=45)
    public String getNajblizi() {
        return this.najblizi;
    }
    
    public void setNajblizi(String najblizi) {
        this.najblizi = najblizi;
    }

    
    @Column(name="Iznajmljeno", length=45)
    public String getIznajmljeno() {
        return this.iznajmljeno;
    }
    
    public void setIznajmljeno(String iznajmljeno) {
        this.iznajmljeno = iznajmljeno;
    }




}


