package pojo;
// Generated Aug 20, 2017 6:05:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Licenca generated by hbm2java
 */
@Entity
@Table(name="Licenca"
    ,catalog="let1"
)
public class Licenca  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String licenca;
     private String name;
     private String surname;
     private String email;

    public Licenca() {
    }

    public Licenca(String username, String licenca, String name, String surname, String email) {
       this.username = username;
       this.licenca = licenca;
       this.name = name;
       this.surname = surname;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="licenca", length=45)
    public String getLicenca() {
        return this.licenca;
    }
    
    public void setLicenca(String licenca) {
        this.licenca = licenca;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


