package pojo;
// Generated Sep 1, 2017 2:28:10 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RadarCentar generated by hbm2java
 */
@Entity
@Table(name="RadarCentar"
    ,catalog="let1"
)
public class RadarCentar  implements java.io.Serializable {


     private Integer id;
     private String let;
     private Double lat;
     private Double lng;
     private String naziv;

    public RadarCentar() {
    }

    public RadarCentar(String let, Double lat, Double lng, String naziv) {
       this.let = let;
       this.lat = lat;
       this.lng = lng;
       this.naziv = naziv;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Let", length=45)
    public String getLet() {
        return this.let;
    }
    
    public void setLet(String let) {
        this.let = let;
    }

    
    @Column(name="Lat", precision=22, scale=0)
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }

    
    @Column(name="Lng", precision=22, scale=0)
    public Double getLng() {
        return this.lng;
    }
    
    public void setLng(Double lng) {
        this.lng = lng;
    }

    
    @Column(name="Naziv", length=45)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }




}


