package pojo;
// Generated Aug 28, 2017 11:00:59 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rezervacija generated by hbm2java
 */
@Entity
@Table(name="Rezervacija"
    ,catalog="let1"
)
public class Rezervacija  implements java.io.Serializable {


     private Integer id;
     private String ime;
     private String prezime;
     private String pasos;
     private String brojLeta;
     private String odakle;
     private String dokle;
     private String idCard;

    public Rezervacija() {
    }

    public Rezervacija(String ime, String prezime, String pasos, String brojLeta, String odakle, String dokle, String idCard) {
       this.ime = ime;
       this.prezime = prezime;
       this.pasos = pasos;
       this.brojLeta = brojLeta;
       this.odakle = odakle;
       this.dokle = dokle;
       this.idCard = idCard;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Ime", length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="Prezime", length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="Pasos", length=45)
    public String getPasos() {
        return this.pasos;
    }
    
    public void setPasos(String pasos) {
        this.pasos = pasos;
    }

    
    @Column(name="BrojLeta", length=45)
    public String getBrojLeta() {
        return this.brojLeta;
    }
    
    public void setBrojLeta(String brojLeta) {
        this.brojLeta = brojLeta;
    }

    
    @Column(name="Odakle", length=45)
    public String getOdakle() {
        return this.odakle;
    }
    
    public void setOdakle(String odakle) {
        this.odakle = odakle;
    }

    
    @Column(name="Dokle", length=45)
    public String getDokle() {
        return this.dokle;
    }
    
    public void setDokle(String dokle) {
        this.dokle = dokle;
    }

    
    @Column(name="IdCard", length=45)
    public String getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }




}


