package pojo;
// Generated Aug 21, 2017 1:07:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TerminalGejt generated by hbm2java
 */
@Entity
@Table(name="TerminalGejt"
    ,catalog="let1"
)
public class TerminalGejt  implements java.io.Serializable {


     private Integer id;
     private String terminal;
     private String gejt;
     private String airport;

    public TerminalGejt() {
    }

    public TerminalGejt(String terminal, String gejt, String airport) {
       this.terminal = terminal;
       this.gejt = gejt;
       this.airport = airport;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Terminal", length=45)
    public String getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

    
    @Column(name="Gejt", length=45)
    public String getGejt() {
        return this.gejt;
    }
    
    public void setGejt(String gejt) {
        this.gejt = gejt;
    }

    
    @Column(name="Airport", length=45)
    public String getAirport() {
        return this.airport;
    }
    
    public void setAirport(String airport) {
        this.airport = airport;
    }




}


