package pojo;
// Generated Sep 4, 2017 4:46:16 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tip generated by hbm2java
 */
@Entity
@Table(name="Tip"
    ,catalog="let1"
)
public class Tip  implements java.io.Serializable {


     private Integer id;
     private String naziv;
     private Integer maxBrojSedista;
     private String licenca;

    public Tip() {
    }

    public Tip(String naziv, Integer maxBrojSedista, String licenca) {
       this.naziv = naziv;
       this.maxBrojSedista = maxBrojSedista;
       this.licenca = licenca;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Naziv", length=45)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="MaxBrojSedista")
    public Integer getMaxBrojSedista() {
        return this.maxBrojSedista;
    }
    
    public void setMaxBrojSedista(Integer maxBrojSedista) {
        this.maxBrojSedista = maxBrojSedista;
    }

    
    @Column(name="Licenca", length=45)
    public String getLicenca() {
        return this.licenca;
    }
    
    public void setLicenca(String licenca) {
        this.licenca = licenca;
    }




}


